version: "3.8"

name: news_service
services:
  goose:
    build:
      context: ../db
      dockerfile: Dockerfile
    pull_policy: never
    image: migrator
  maindb:
    container_name: maindb
    image: postgres:16
    environment:
      POSTGRES_USER: ${MAINDB_USERNAME}
      POSTGRES_PASSWORD: ${MAINDB_PASSWORD}
      POSTGRES_DB: ${MAINDB_DBNAME}
    ports:
      - "${MAINDB_PORT}:5432"
    restart: always
    depends_on:
      - goose
    volumes:
      - main_data:/var/lib/postgresql/data
  maindb-migrator:
    container_name: maindb-migrator
    image: migrator
    pull_policy: never
    command: [ "postgresql://${MAINDB_USERNAME}:${MAINDB_PASSWORD}@maindb:5432/${MAINDB_DBNAME}", "up" ]
    volumes:
      - ../db/migrations:/migrations
volumes:
  main_data: